### PR TITLE
Add support of XT1079

### PR DESCRIPTION
**Pull request by twtvfhpfm**
Add support of XT1079

### CODE REVIEW

**Comment by luk1337** [comment]
Thank you, I'll build rom later cuz im going to school in 1 hour

**Comment by twtvfhpfm** [comment]
Hi! Where can I download the rom? Will thea be officially supported by CyanogenMod?

**Comment by luk1337** [comment]
You can download it from my basketbuild (find on XDA) and yes It will be
supported in future.

**Comment by luca020400** [comment]
Can you provide full build.prop ?
Probably we need other other props for XT1079 - Retail China - TD-SCDMA

**Comment by twtvfhpfm** [comment]
# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=LXB22.99-7.1
ro.build.display.id=LXB22.99-7.1
ro.build.version.incremental=1
ro.build.version.sdk=21
ro.build.version.codename=REL
ro.build.version.all_codenames=REL
ro.build.version.release=5.0.2
ro.build.date=Wed Feb  4 17:20:43 CST 2015
ro.build.date.utc=1423092043
ro.build.type=user
ro.build.user=hudsoncm
ro.build.host=ilclbld53
ro.build.tags=release-keys
ro.product.model=XT1079
ro.product.brand=motorola
ro.product.name=thea_retcn_ds
ro.product.device=thea_ds
ro.product.board=MSM8226
# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,
# use ro.product.cpu.abilist instead.
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.cpu.abilist=armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=
ro.product.manufacturer=motorola
ro.wifi.channels=
ro.board.platform=msm8226
# ro.build.product is obsolete; use ro.product.device
ro.build.product=thea_ds
# Do not try to parse description, fingerprint, or thumbprint
ro.build.description=thea_retcn_ds-user 5.0.2 LXB22.99-7.1 1 release-keys
ro.build.fingerprint=motorola/thea_retcn_ds/thea_ds:5.0.2/LXB22.99-7.1/1:user/release-keys
ro.build.characteristics=default
# end build properties
#
# from device/moto/thea_ds/system.prop
#
#
# system.prop for msm8226
#

# Use reference RIL for initial bringup
#rild.libpath=/system/lib/libreference-ril.so
rild.libpath=/vendor/lib/libril-qc-qmi-1.so
rild.libargs=-d /dev/smd0
persist.radio.nitz_plmn=
persist.radio.nitz_lons_0=
persist.radio.nitz_lons_1=
persist.radio.nitz_lons_2=
persist.radio.nitz_lons_3=
persist.radio.nitz_sons_0=
persist.radio.nitz_sons_1=
persist.radio.nitz_sons_2=
persist.radio.nitz_sons_3=
ril.subscription.types=NV,RUIM
DEVICE_PROVISIONED=1
persist.radio.msgtunnel.start=false
persist.radio.manual_mode_timer=60

#
# system props for the cne module
#
persist.cne.feature=0

# Skip /sys/power/wait_for_fb_\* nodes and
# force FB to be always on
debug.sf.fb_always_on=1

debug.sf.hw=1
debug.egl.hw=1
debug.composition.type=c2d
persist.hwc.mdpcomp.enable=true
debug.mdpcomp.logs=0
dalvik.vm.heapsize=36m
dev.pm.dyn_samplingrate=1

persist.demo.hdmirotationlock=false
ro.hdmi.enable=true
tunnel.decode=false
tunnel.audiovideo.decode=false
lpa.decode=true
lpa.use-stagefright=true

#system props for the MM modules

media.stagefright.enable-player=true
media.stagefright.enable-http=true
media.stagefright.enable-aac=true
media.stagefright.enable-qcp=true
media.stagefright.enable-fma2dp=true
media.stagefright.enable-scan=true
mmp.enable.3g2=true
#9273 is decimal sum of supported codecs in AAL
#codecs:(PARSER_)AVI AC3 ASF AAC QCP DTS 3G2 MP2TS
mm.enable.qcom_parser=37491

# VIDC: debug_levels
# 1:ERROR 2:HIGH 4:LOW 0:NOlogs 7:AllLogs
vidc.debug.level=1

#
# system props for the data modules
#
ro.use_data_netmgrd=true

#system props for time-services
persist.timed.enable=true

#
# system prop for opengles version
#
# 196608 is decimal for 0x30000 to report version 3
ro.opengles.version=196608

#
# System props for telephony
# System prop to turn on CdmaLTEPhone always
telephony.lteOnCdmaDevice=0

# simulate sdcard on /data/media
#
persist.fuse_sdcard=false
persist.esdfs_sdcard=true
ro.crypto.fuse_sdcard=true

#
#snapdragon value add features
#
# System props for audio
ro.qc.sdk.audio.ssr=false
##fluencetype can be "fluence" or "fluencepro" or "none"
persist.audio.fluence.mode=endfire
persist.audio.handset.mic=digital
ro.config.vc_call_vol_steps=7
# FM maximum volume be between 0 and 8192 (0dB)
ro.audio.fm_max_volume=4096

#need rotation info in audio-land
ro.audio.monitorRotation=1

# Enable/disable cabl
ro.qualcomm.cabl=0

# system prop for NFC DT
ro.nfc.port=I2C

#
# system property for Bluetooth hci transport
#
ro.qualcomm.bt.hci_transport=smd

#
# system property for Bluetooth HFP version
#
ro.bluetooth.hfp.ver=1.6

#
# system property for Bluetooth SAP support
# Motorola disabled SAP
#
ro.qualcomm.bluetooth.sap=false

# Bluetooth LE power class
qcom.bt.le_dev_pwr_class=1

##property to choose between virtual/external wfd display
persist.sys.wfd.virtual=0
# Motorola, ams087, 09/24/2013, IKJBMR2-6432 : disable tunnel audio encode
#tunnel.audio.encode = true

# Enable SSR
persist.sys.ssr.restart_level=3
persist.sys.qc.sub.rdump.on=1

# For TCMD debug level
persist.tcmd.log.limit=0

# Disable QCOM net early sockets feature
net.early.sockets=0

# Radio RIL properties
persist.radio.no_wait_for_card=1
persist.radio.apm_sim_not_pwdn=1
persist.radio.dfr_mode_set=1
persist.radio.relay_oprt_change=1

#Enable offload audio playback by default
audio.offload.disable=0

#Disable offload audio video playback by default
av.offload.enable=false

#
# ADDITIONAL_BUILD_PROPERTIES
#
ro.product.display=Moto G
ro.build.version.qcom=AU_LINUX_ANDROID_LNX.LA.3.5.1_RB1.04.04.02.048.045
ro.mot.build.customerid=retcn
ro.mot.build.version.sdk_int=22
ro.build.version.full=Blur_Version.22.36.1.thea_retcn_ds.retcn.en.CN
persist.radio.mcfg_enabled=1
persist.radio.mbn_path=/fsg/
persist.radio.multi_mbns=cu.mbn;cmcc.mbn
ro.telephony.default_network=20
ro.lenovo.adb=apkctl
ro.product.locale.language=zh
ro.product.locale.region=CN
ro.telephony.append_ecclist=110,119,112,122,120,911
persist.radio.rat_on=combine
persist.mot.gps.assisted=false
ro.mot.inc.ruim.priority=true
persist.radio.redir_party_num=0
ro.cdma.subscription=0
ro.telephony.default_cdma_sub=0
ril.subscription.types=RUIM
telephony.lteOnCdmaDevice=1
ro.com.android.dataroaming=false
persist.radio.multisim.config=dsds
persist.radio.dont_use_dsd=true
ro.MAX_HIDDEN_APPS=12
dalvik.vm.heapstartsize=8m
dalvik.vm.heapgrowthlimit=96m
dalvik.vm.heapsize=256m
dalvik.vm.heaptargetutilization=0.75
dalvik.vm.heapminfree=2m
dalvik.vm.heapmaxfree=8m
persist.sys.logkit.ctrlcode=0
ro.vendor.extension_library=/vendor/lib/libqc-opt.so
persist.radio.apm_sim_not_pwdn=1
ro.usb.mtp=0x2e82
ro.usb.mtp_adb=0x2e76
ro.usb.ptp=0x2e83
ro.usb.ptp_adb=0x2e84
ro.usb.bpt=0x2e28
ro.usb.bpt_adb=0x2e29
ro.usb.bpteth=0x2e2a
ro.usb.bpteth_adb=0x2e2b
persist.audio.calfile0=/etc/Bluetooth_cal.acdb
persist.audio.calfile1=/etc/General_cal.acdb
persist.audio.calfile2=/etc/Global_cal.acdb
persist.audio.calfile3=/etc/Handset_cal.acdb
persist.audio.calfile4=/etc/Hdmi_cal.acdb
persist.audio.calfile5=/etc/Headset_cal.acdb
persist.audio.calfile6=/etc/Speaker_cal.acdb
ro.bug2go.magickeys=24,26
persist.sys.qc.sub.rdump.max=0
ro.adb.secure=1
ro.sf.lcd_density=320
ro.frp.pst=/dev/block/platform/msm_sdcc.1/by-name/frp
ro.config.ringtone=Moto.ogg
ro.config.notification_sound=Moto.ogg
ro.config.alarm_alert=Oxygen.ogg
persist.radio.apn_delay=5000
persist.sys.media.use-awesome=false
keyguard.no_require_sim=true
drm.service.enabled=true
mdc_initial_max_retry=10
ro.persist.qcapb=1
ro.com.google.clientidbase=android-motorola
ro.com.google.clientidbase.ms=android-motorola
ro.com.google.clientidbase.am=android-motorola
ro.com.google.clientidbase.gmm=android-motorola
ro.com.google.clientidbase.yt=android-motorola
ro.carrier=unknown
ro.media.enc.aud.fileformat=amr
ro.media.enc.aud.codec=amrnb
persist.sys.dalvik.vm.lib.2=libart.so
dalvik.vm.isa.arm.features=div
net.bt.name=Android
dalvik.vm.stack-trace-file=/data/anr/traces.txt
ro.qc.sdk.izat.premium_enabled=0
ro.qc.sdk.izat.service_mask=0x0
persist.gps.qc_nlp_in_use=0
ro.gps.agps_provider=1

**Comment by luk1337** [comment]
@twtvfhpfm could you test that build? https://basketbuild.com/filedl/devs?dev=LuK1337&dl=LuK1337/CM12.1/thea/cm-12.1-20150423-UNOFFICIAL-thea.zip if you run into problems get on IRC (#titandev on freenode)

**Comment by twtvfhpfm** [comment]
Ok, I'll flash it tonight, thank you.

**Pull request merged**
